# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_b:
    has_velocity_limits: true
    max_velocity: 3.8135445205
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_l:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_r:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_s:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_t:
    has_velocity_limits: true
    max_velocity: 5.8032199225
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_u:
    has_velocity_limits: true
    max_velocity: 3.31612567
    has_acceleration_limits: false
    max_acceleration: 0
