controller_list:
  - name: fake_Arm_controller
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
  - name: fake_Mount_controller
    joints:
      - bod_base_link
      - link_JOINT_1
  - name: fake_Hand_controller
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r