# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
motomini_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1_s
    - joint_2_l
    - joint_3_u
    - joint_4_r
    - joint_5_b
    - joint_6_t
  constraints:
      stopped_velocity_tolerance: 0
      joint_1_s: {trajectory: 0.1, goal: 0}
      joint_2_l: {trajectory: 0.1, goal: 0}
      joint_3_u: {trajectory: 0.1, goal: 0}
      joint_4_r: {trajectory: 0.1, goal: 0}
      joint_5_b: {trajectory: 0.1, goal: 0}
      joint_6_t: {trajectory: 0.1, goal: 0}